[build]
  publish = "public"
  command = "cd client && npm install && npm run build && cd .. && hugo --minify"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.139.4"
  NODE_VERSION = "18"

[build.environment]
  HUGO_VERSION = "0.139.4"
  NODE_VERSION = "18"

[build.deploy]
  base = "/"

[[redirects]]
  from = "/.netlify/*"
  to = "https://www.fair-protocol.netlify.app/:splat"
  status = 301
  force = true