[build]
  publish = "public"
  command = """
    cd client && \
    npm install && \
    npm run build && \
    cd .. && \
    mkdir -p static/dist && \
    cp client/dist/fair-protocol.js static/dist/ && \
    hugo --minify
  """

[build.environment]
  HUGO_VERSION = "0.139.4"
  NODE_VERSION = "18"

[context.production]
  [context.production.environment]
    HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404